name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Create .env.production from repo vars/secrets
        run: |
          {
            echo "VITE_SUPABASE_URL=${{ vars.VITE_SUPABASE_URL || secrets.VITE_SUPABASE_URL }}"
            echo "VITE_SUPABASE_ANON_KEY=${{ vars.VITE_SUPABASE_ANON_KEY || secrets.VITE_SUPABASE_ANON_KEY }}"
          } > .env.production

      - name: Validate env file
        run: |
          echo "--- .env.production (masked) ---"
          awk -F= 'BEGIN{OFS="="} $1=="VITE_SUPABASE_ANON_KEY"{print $1, substr($2,1,6)"... (len="length($2)")"; next} {print $0}' .env.production
          test -s .env.production || (echo "ERROR: .env.production missing or empty" && exit 1)
          grep -q '^VITE_SUPABASE_URL=' .env.production || (echo "ERROR: VITE_SUPABASE_URL missing" && exit 1)
          grep -q '^VITE_SUPABASE_ANON_KEY=' .env.production || (echo "ERROR: VITE_SUPABASE_ANON_KEY missing" && exit 1)

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          echo "Using Vite mode=production (loads .env.production)"
          npm run build -- --mode production
          cp dist/index.html dist/404.html

      - name: Verify build embeds Supabase envs
        run: |
          echo '--- GREP SUPABASE URL IN DIST ---'
          grep -R "supabase.co" -n dist
          echo '--- VERIFY no unresolved import.meta.env in dist (should be empty) ---'
          ! grep -RE 'import\.meta\.env\.VITE_SUPABASE_(URL|ANON_KEY)' -n dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
